spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug

---
spring.profiles: set1
spring.profiles.include: real-db
server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db
server:
  port: 8082