spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true


  #logging.level:
  #org.hibernate.SQL: debug
  #org.hibernate.type: trace
my-app:
  client-id: myApp
  client-secret: password

---
spring.profiles: set1
spring.profiles.include: real-db
server:
  port: 8081

my-app:
  client-id: myApp
  client-secret: password
---
spring.profiles: set2
spring.profiles.include: real-db
server:
  port: 8082

my-app:
  client-id: myApp
  client-secret: password